### About Dataset: 
This is about prediction of a Glass type based on the on its constituents/content.

### Importing libraries and packages

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline


### Read the data from axcel form

In [2]:
data=pd.read_excel("glass.xlsx")

In [3]:
X,y=data.iloc[:,1:10], data["Prod_Type"]

In [4]:
X.info()
X.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 9 columns):
RI    214 non-null float64
Na    214 non-null float64
Mg    214 non-null float64
Al    214 non-null float64
Si    214 non-null float64
K     214 non-null float64
Ca    214 non-null float64
Ba    214 non-null float64
Fe    214 non-null float64
dtypes: float64(9)
memory usage: 15.2 KB


(214, 9)

In [5]:
y.shape

(214,)

In [6]:
print(y.unique())#unique values from the target feature

[1 2 3 5 6 7]


In [7]:
y.isnull().sum()

0

##### Considering the data is cleaned and not performing the necessary EDA and Feature selection and extraction. This is just to learn how to use Classification models

### Preparing the train set and test set

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(X,y, test_size=0.25, random_state=42)

### creating SVM with Radial Kernel

In [9]:
from sklearn.svm import SVC
model_rbf =SVC(kernel='rbf', random_state=42)
model_rbf.fit(X_train, y_train)

C:\Users\kishan\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=42,
    shrinking=True, tol=0.001, verbose=False)

##### Check Performance

In [10]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
y_pred=model_rbf.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, model_rbf.predict(X_test)))

0.6481481481481481
[[14  0  0  0  0  0]
 [10 10  0  1  0  0]
 [ 4  0  0  0  0  0]
 [ 0  1  0  3  0  0]
 [ 0  2  0  0  1  0]
 [ 0  0  0  0  1  7]]
              precision    recall  f1-score   support

           1       0.50      1.00      0.67        14
           2       0.77      0.48      0.59        21
           3       0.00      0.00      0.00         4
           5       0.75      0.75      0.75         4
           6       0.50      0.33      0.40         3
           7       1.00      0.88      0.93         8

    accuracy                           0.65        54
   macro avg       0.59      0.57      0.56        54
weighted avg       0.66      0.65      0.62        54



C:\Users\kishan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


##### The radial SVM provides much less accuracy ie, 65%. Lets apply some other classification models

##### (n)  in a multiclass , we see the F1 score, Precision, and Recall

### Creating SVM Linear Kernel `m


In [11]:
model_lin=SVC(kernel='linear', random_state=42)
model_lin.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=42,
    shrinking=True, tol=0.001, verbose=False)

In [12]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
y_pred=model_lin.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, model_lin.predict(X_test)))# the point lying within the hyperplane from 0 to distance w/2

0.6481481481481481
[[13  1  0  0  0  0]
 [ 8 11  0  0  1  1]
 [ 3  1  0  0  0  0]
 [ 0  1  0  3  0  0]
 [ 0  1  0  1  1  0]
 [ 0  1  0  0  0  7]]
              precision    recall  f1-score   support

           1       0.54      0.93      0.68        14
           2       0.69      0.52      0.59        21
           3       0.00      0.00      0.00         4
           5       0.75      0.75      0.75         4
           6       0.50      0.33      0.40         3
           7       0.88      0.88      0.88         8

    accuracy                           0.65        54
   macro avg       0.56      0.57      0.55        54
weighted avg       0.62      0.65      0.62        54



C:\Users\kishan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


### Creating SVM with poly

In [13]:
model_rbf =SVC(kernel='poly', gamma =0.1, C=0.8, degree = 2)
model_rbf.fit(X_train, y_train)

SVC(C=0.8, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=2, gamma=0.1, kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [14]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
y_pred=model_rbf.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, model_rbf.predict(X_test)))# the point lying within the hyperplane from 0 to distance w/2

0.7592592592592593
[[13  1  0  0  0  0]
 [ 4 15  0  0  2  0]
 [ 3  1  0  0  0  0]
 [ 0  0  0  4  0  0]
 [ 0  0  0  1  2  0]
 [ 1  0  0  0  0  7]]
              precision    recall  f1-score   support

           1       0.62      0.93      0.74        14
           2       0.88      0.71      0.79        21
           3       0.00      0.00      0.00         4
           5       0.80      1.00      0.89         4
           6       0.50      0.67      0.57         3
           7       1.00      0.88      0.93         8

    accuracy                           0.76        54
   macro avg       0.63      0.70      0.65        54
weighted avg       0.74      0.76      0.74        54



C:\Users\kishan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


##### The poly-SVM provides a little better  accuracy ie, 76%. Lets apply some other classification models

### Random Forest

In [15]:
from sklearn.ensemble import RandomForestClassifier#dont increase no. of trees if accuracy does not increase
rf1=RandomForestClassifier(n_estimators=50, criterion='gini', max_depth=4, random_state=42)
rf1.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=4, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=50,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [16]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
y_pred=rf1.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, rf1.predict(X_test)))

0.7407407407407407
[[14  0  0  0  0  0]
 [ 6 11  0  2  1  1]
 [ 3  0  1  0  0  0]
 [ 0  1  0  3  0  0]
 [ 0  0  0  0  3  0]
 [ 0  0  0  0  0  8]]
              precision    recall  f1-score   support

           1       0.61      1.00      0.76        14
           2       0.92      0.52      0.67        21
           3       1.00      0.25      0.40         4
           5       0.60      0.75      0.67         4
           6       0.75      1.00      0.86         3
           7       0.89      1.00      0.94         8

    accuracy                           0.74        54
   macro avg       0.79      0.75      0.71        54
weighted avg       0.81      0.74      0.72        54



### Decision Tree

In [17]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(criterion='gini', max_depth=3, random_state=42)
dt.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=42, splitter='best')

In [18]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
y_pred=dt.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, dt.predict(X_test)))

0.7222222222222222
[[13  1  0  0  0  0]
 [ 5 14  0  2  0  0]
 [ 3  1  0  0  0  0]
 [ 0  0  0  4  0  0]
 [ 0  1  0  2  0  0]
 [ 0  0  0  0  0  8]]
              precision    recall  f1-score   support

           1       0.62      0.93      0.74        14
           2       0.82      0.67      0.74        21
           3       0.00      0.00      0.00         4
           5       0.50      1.00      0.67         4
           6       0.00      0.00      0.00         3
           7       1.00      1.00      1.00         8

    accuracy                           0.72        54
   macro avg       0.49      0.60      0.52        54
weighted avg       0.67      0.72      0.68        54



C:\Users\kishan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


### KNN Classifier

In [19]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5,p=3) #type of distance, p=3, it is for minwoski distance
#p=2=> Eucledean Distance
#p=1=>Manhattan Distance
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=3,
                     weights='uniform')

In [20]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
y_pred=knn.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, knn.predict(X_test)))

0.6111111111111112
[[12  1  1  0  0  0]
 [ 6 11  1  1  2  0]
 [ 4  0  0  0  0  0]
 [ 0  1  0  2  0  1]
 [ 0  1  0  0  1  1]
 [ 0  0  0  0  1  7]]
              precision    recall  f1-score   support

           1       0.55      0.86      0.67        14
           2       0.79      0.52      0.63        21
           3       0.00      0.00      0.00         4
           5       0.67      0.50      0.57         4
           6       0.25      0.33      0.29         3
           7       0.78      0.88      0.82         8

    accuracy                           0.61        54
   macro avg       0.50      0.51      0.50        54
weighted avg       0.63      0.61      0.60        54



### Logistic Regresion (it works on Multinomial Distribution)

In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score


In [22]:
log_reg=LogisticRegression()
log_reg.fit(X_train, y_train)

C:\Users\kishan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\kishan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [23]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
y_pred=log_reg.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, log_reg.predict(X_test)))

0.5925925925925926
[[12  2  0  0  0  0]
 [ 9 11  0  0  0  1]
 [ 3  1  0  0  0  0]
 [ 0  3  0  1  0  0]
 [ 0  1  0  0  0  2]
 [ 0  0  0  0  0  8]]
              precision    recall  f1-score   support

           1       0.50      0.86      0.63        14
           2       0.61      0.52      0.56        21
           3       0.00      0.00      0.00         4
           5       1.00      0.25      0.40         4
           6       0.00      0.00      0.00         3
           7       0.73      1.00      0.84         8

    accuracy                           0.59        54
   macro avg       0.47      0.44      0.41        54
weighted avg       0.55      0.59      0.54        54



C:\Users\kishan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


### Conclusion: The maximum accuracy was from SVM with 'Ploy' kernel i.e, 76%. So we will use this to perform the predictions

#### The more you can do is:
    # Use other classification models
    # Use hypertuning the models parameters
    # Use feature selection or extractions 
    # Choose a larger dataset
    # Use Ensemble techniques